name: Examples Overlap

# Controls when the workflow will run
on:
  # Triggers the workflow on all pushes
  push:
  pull_request:
    types:
      # only run workflow when a commit is pushed to a PR branch
      # instead of running for all other PR events
      - synchronize

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # Build the geometry and plugins, runs jcard in overlaps directory
  overlap:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: jeffersonlab/gemc:3.0
    name: Overlap Tests ${{ matrix.example }}
    strategy:
      fail-fast: false
      matrix:
        example:
          - examples/geometry/simple_flux
          - examples/geometry/dosimeter

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: ${{ matrix.example }} overlap
        run: |
          ./ci/tests.sh -e ${{ matrix.example }} -o

 
